---
title: "Assignment3 - Covid19: vaccination rates, case numbers, and death rates compare across France, Canada, Germany, India, the UK, and the US"
format: 
  html: default
  pdf: default
editor: visual
author: 
  - name: "Midhun Unnikrishnan"
    affiliation: "GitHub: @MidhunUnnikrishnan7"
  - name: "Sumintra Boonmat"
    affiliation: "GitHub: @SumintraB"
  - name: "Lin Qi"
    affiliation: "GitHub: @linqi70"
---

## Table of contents

## Executive summary

## Introduction

## Methodology (with figure and table + references)

## Results (with either a figure or table)

```{r message=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

### Case Rate

### Vaccination

### Death Rate

```{r}
cases_deaths <- read_csv("data/cases_deaths.csv") |>
  filter(country %in% c("United Kingdom", "Canada", "France", "Germany", "India", "United States")) |>
  filter(date >= as.Date("2020-02-01") & date <= as.Date("2023-02-01")) |>
  select(country, date, total_deaths)
```

```{r}
#| label: fig-death-rate
#| fig-cap: "COVID-19 daily death confirmed: by country"
ggplot(cases_deaths, aes(x = date, y = total_deaths, color = country)) +
  geom_line() +
  labs(title = "Daily COVID-19 Death Rates",
       x = "Date", y = "Total Deaths")
```

## Discussion, conclusion, recommendations

## Reference section
