---
format:
  revealjs:
    theme: simple
    title-slide: false
---

##
::: {style="text-align: center; margin-top: 15vh;"}
## <span style="font-size: 1.4em;">COVID-19 Impact Analysis:</span><br>
<span style="font-size: 1.3em;">Cases, Deaths, and Vaccination Rates</span>

<br>

<span style="color: #111184;">Lin Qi</span><br>
<span style="color: #111184;">Midhun Unnikrishnan</span><br>
<span style="color: #111184;">Sumintra Boonmat</span>
:::

---

## <span style="color: #111184;">Problem Introduction</span>
<hr style="border: 1px solid #f5f5f5;">

::: {.fragment style="font-size: 60%;"}
- COVID-19 began spreading worldwide since early 2020, countries have experienced with varying severity.
- Governments responded with ***testing***, ***lockdowns***, and ***vaccines***, but results varied.
:::


::: {.fragment}
<span style="font-size: 70%; font-weight: bold;">Research question</span>
<div style="border: 2px solid #111184; border-radius: 8px; padding: 15px; font-size: 60%; background-color: #f5f5f5;">
How COVID-19 changed over time across six different countries, and whether vaccines helped reduce cases and deaths.
</div>
:::


::: {.fragment style="font-size: 60%;"}
- The study focuses on 6 countries:
    - **Canada**
    - **France**
    - **Germany**
    - **India**
    - **United Kingdom**
    - **United States**
:::
------------------------------------------------------------------------

## <span style="color: #111184;">Dataset Description</span>
<hr style="border: 1px solid #f5f5f5;">

::: {.fragment style="font-size: 70%;"}
- **Data Includes:**
    - Daily confirmed COVID-19 cases
    - COVID-19 deaths
    - Vaccination rates
:::

::: {.fragment style="font-size: 70%;"}
- **Source:** [Our World in Data](https://ourworldindata.org/)
:::

::: {.fragment style="font-size: 70%;"}
- **Time Period:**  
    - February 2020 – February 2023  
    - January 16, 2021 – September 4, 2022 (Vaccination Rates)
:::


------------------------------------------------------------------------

## <span style="color: #111184;">Methods</span>
<hr style="border: 1px solid #f5f5f5;">

::: {.fragment style="font-size: 80%;"}
- **Data Source**: 
COVID-19 cases, deaths, and vaccination rates data from Our World in Data.

- **Data Cleaning & Processing:** 
filtering and cleaning data using R, removing missing values.
:::
::: {.fragment style="font-size: 80%;"}
- **Selected Countries for Comparison:** 
Canada, France, Germany, India, the UK, and the US.

- **Time periods:** 
were aligned to ensure fair comparisons between countries.

- **Analysis:** 
created visualizations to compare trends across cases, deaths, and vaccinations.
:::
---

## Results Summary (will add the plots)

-   **Vaccination Rolled Out After Cases Rose**

-   **Vaccines Helped Reduce Deaths Over Time**

-   **Vaccines Slowed the Spread After Rollout**

---

## Conclusion

::: {.fragment}
After analyzing the COVID-19 cases, deaths, and vaccination data from six different countries.
:::

::: {.fragment}
**Key Findings:**
:::

::: {.fragment}
1. Case numbers often rose before widespread vaccination began.
:::

::: {.fragment}
2. Major outbreaks led to sharp daily changes in both cases and vaccine doses.
:::

::: {.fragment}
3. A 7-day lag analysis showed that higher vaccination rates were followed by fewer new cases, especially where rollout was early and sustained.
:::

